import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import { Sidebar } from "@/components/LandingPage/hero";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "300", "500", "700", "900"],
  variable: "--font-Roboto"
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${roboto.variable} ${geistMono.variable} antialiased flex `}
      >
        <div className="hidden md:flex md:max-w-[20%]  2xl:max-w-[30%] ">
          <Sidebar />
        </div>
        <div className="w-[100%] md:min-w-[80%] overflow-x-hidden">
          {children}
        </div>
      </body>
    </html>
  );
}
